sources:
  - name: threshold-tbtc
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/suntzu93/threshold-tbtc-goerli
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql