sources:
  - name: threshold-tbtc
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/575/threshold-tbtc-testnet/release.0.2
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql