sources:
  - name: threshold-tbtc-mainnet
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/575/threshold-tbtc-mainnet/v0.1.4
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql