sources:
  - name: threshold-tbtc
    handler:
      graphql:
        endpoint: https://gateway.testnet.thegraph.com/api/7cc7a8b42a7f9288f995125f449b432c/subgraphs/id/EAabZitXhygFzb9gXNCvwRvfeNJf2qkffv3Kykhdqbj5
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql